kind: Deployment
apiVersion: apps/v1

metadata:
  name: blueg-framework
  labels:
    app: blueg-framework

spec:
  # 1. How many copies of each pod do we want?
  replicas: 1

  # 2. How do want to update the pods?
  strategy: Recreate

  # 3. Which pods are managed by this deployment?
  selector:
    # This must match the labels we set on the pod!
    matchLabels:
      deploy: blueg-framework
  
  # This template field is a regular pod configuration 
  # nested inside the deployment spec
  template:
    metadata:
      # Set labels on the pod.
      # This is used in the deployment selector.
      labels:
        deploy: blueg-framework
    spec:
      containers:
        - name: blueg-framework
          image: logicalangel/simplehttp
      restartPolicy: Always